sudo: true
dist: trusty
install: true 

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t microsoft/terraform . 
      - pwd
      - docker run --rm microsoft/terraform "rake" 
 