sudo: true
dist: trusty
install: true 

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t microsoft/terraform .
      - mkdir logs
      - docker run -v $PWD/logs:/tf-test/.kitchen --rm microsoft/terraform 
 