sudo: true
dist: trusty
install: true 

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t microsoft/terraform .
      - docker run --rm microsoft/terraform -v $PWD/logs:/tf-test/.kitchen -it tf-test-container
 